// MuFinance — editor de veículo: identidade editorial, seleção visual de tipo e ações claras.
import { Bike, CarFront, ChevronLeft, ChevronRight, Fuel, Gauge, Pencil, Plus, Route, Save, Wrench } from "lucide-react";
import { useMemo, useState } from "react";
import { formatBRL, vehicleFuelEntries, vehicleMaintenanceEntries, vehicleOdometerEntries, type VehicleProfile } from "@/lib/financeData";

type VehiclePageProps = { onBack: () => void; onAction: (label: string) => void; vehicle: VehicleProfile; onVehicleUpdate: (vehicle: VehicleProfile) => void };
type VehicleTab = "overview" | "fuel" | "maintenance" | "odometer";

export function VehiclePage({ onBack, onAction, vehicle, onVehicleUpdate }: VehiclePageProps) {
  const [tab, setTab] = useState<VehicleTab>("overview");
  const [editingVehicle, setEditingVehicle] = useState(false);
  const fuelTotal = vehicleFuelEntries.reduce((sum, item) => sum + item.amount, 0);
  const maintenanceTotal = vehicleMaintenanceEntries.filter((item) => item.status === "concluída").reduce((sum, item) => sum + item.amount, 0);
  const distance = vehicleOdometerEntries[0].odometer - vehicleOdometerEntries[vehicleOdometerEntries.length - 1].odometer;
  const costPerKm = (fuelTotal + maintenanceTotal) / distance;
  const lastOdometer = vehicleOdometerEntries[0].odometer;
  const nextMaintenance = vehicleMaintenanceEntries.find((item) => item.status === "agendada");
  const tabLabel = useMemo(() => ({ overview: "Visão geral", fuel: "Abastecimentos", maintenance: "Manutenção", odometer: "Quilometragem" }[tab]), [tab]);
  const vehicleTypeLabel = vehicle.type === "motorcycle" ? "Moto" : "Carro";

  const saveVehicle = (nextVehicle: VehicleProfile) => {
    onVehicleUpdate(nextVehicle);
    setEditingVehicle(false);
    onAction("Veículo atualizado");
  };

  return <section className="dedicated-page vehicle-page">
    <div className="dedicated-page-header vehicle-page-header"><div><button className="back-link" type="button" onClick={onBack}><ChevronLeft size={16} /> Voltar para início</button><p className="eyebrow">MOBILIDADE · {tabLabel.toUpperCase()}</p><h1>Seu veículo em movimento.</h1><p className="page-subtitle">Um espaço para acompanhar custos, uso e próximos cuidados sem misturar mobilidade com o restante do extrato.</p></div><div className="dedicated-page-actions"><button className="soft-button" type="button" onClick={() => setEditingVehicle((current) => !current)}><Pencil size={15} /> {editingVehicle ? "Fechar edição" : "Editar veículo"}</button><button className="soft-button" type="button" onClick={() => onAction("Quilometragem")}><Gauge size={15} /> Registrar km</button><button className="primary-button" type="button" onClick={() => onAction("Abastecimento")}><Plus size={15} /> Novo registro</button></div></div>
    {editingVehicle ? <VehicleIdentityEditor vehicle={vehicle} onCancel={() => setEditingVehicle(false)} onSave={saveVehicle} /> : <div className="vehicle-identity-card"><div className="vehicle-avatar"><CarFront size={28} /></div><div><span className="vehicle-status"><i /> Ativo · uso pessoal</span><h2>{vehicle.manufacturer} {vehicle.model}</h2><p>{vehicleTypeLabel} · {vehicle.year} · {vehicle.fuel} · {vehicle.city}</p></div><div className="vehicle-identity-meta"><span>Odômetro atual</span><strong>{lastOdometer.toLocaleString("pt-BR")} km</strong><small>último registro · 12 ago</small></div></div>}
    <div className="vehicle-tabs" role="tablist" aria-label="Detalhes do veículo">{([ ["overview", "Visão geral", CarFront], ["fuel", "Abastecimentos", Fuel], ["maintenance", "Manutenção", Wrench], ["odometer", "Quilometragem", Route] ] as const).map(([value, label, Icon]) => <button type="button" role="tab" aria-selected={tab === value} className={tab === value ? "is-active" : ""} key={value} onClick={() => setTab(value)}><Icon size={15} /> {label}</button>)}</div>
    {tab === "overview" && <><div className="vehicle-kpi-grid"><article className="vehicle-kpi vehicle-kpi--mint"><span><Fuel size={16} /> Combustível no período</span><strong>{formatBRL(fuelTotal)}</strong><small>121,1 litros registrados</small></article><article className="vehicle-kpi vehicle-kpi--lavender"><span><Wrench size={16} /> Manutenção realizada</span><strong>{formatBRL(maintenanceTotal)}</strong><small>1 serviço concluído</small></article><article className="vehicle-kpi vehicle-kpi--peach"><span><Route size={16} /> Custo por km</span><strong>{formatBRL(costPerKm)}</strong><small>{distance.toLocaleString("pt-BR")} km acompanhados</small></article></div><div className="vehicle-detail-grid"><article className="surface-card vehicle-activity-card"><div className="card-header"><div><p className="eyebrow">ATIVIDADE RECENTE</p><h2>Últimos cuidados</h2><p className="card-subtitle">O que aconteceu com seu veículo.</p></div><button className="text-button" type="button" onClick={() => setTab("maintenance")}>Ver histórico <ChevronRight size={14} /></button></div><div className="vehicle-timeline"><div className="vehicle-timeline-item"><span className="vehicle-timeline-icon vehicle-timeline-icon--mint"><Fuel size={15} /></span><div><strong>{vehicleFuelEntries[0].station}</strong><small>{vehicleFuelEntries[0].date} · {vehicleFuelEntries[0].liters.toFixed(1).replace(".", ",")} L</small></div><b>{formatBRL(vehicleFuelEntries[0].amount)}</b></div><div className="vehicle-timeline-item"><span className="vehicle-timeline-icon vehicle-timeline-icon--lavender"><Wrench size={15} /></span><div><strong>{vehicleMaintenanceEntries[0].title}</strong><small>{vehicleMaintenanceEntries[0].date} · {vehicleMaintenanceEntries[0].workshop}</small></div><b>{formatBRL(vehicleMaintenanceEntries[0].amount)}</b></div></div></article><article className="surface-card vehicle-next-card"><p className="eyebrow">PRÓXIMO CUIDADO</p><h2>{nextMaintenance?.title}</h2><p>{nextMaintenance?.date} · {nextMaintenance?.workshop}</p><div className="vehicle-next-amount"><span>Previsão de custo</span><strong>{formatBRL(nextMaintenance?.amount ?? 0)}</strong></div><button className="primary-button primary-button--small" type="button" onClick={() => onAction("Manutenção")}><CalendarIcon /> Abrir lembrete</button></article></div></>}
    {tab === "fuel" && <VehicleFuelTable onAction={onAction} />}
    {tab === "maintenance" && <VehicleMaintenanceTable onAction={onAction} />}
    {tab === "odometer" && <VehicleOdometerTable onAction={onAction} />}
  </section>;
}

function VehicleIdentityEditor({ vehicle, onCancel, onSave }: { vehicle: VehicleProfile; onCancel: () => void; onSave: (vehicle: VehicleProfile) => void }) {
  const [draft, setDraft] = useState<VehicleProfile>(vehicle);
  const [error, setError] = useState("");
  const update = <K extends keyof VehicleProfile>(key: K, value: VehicleProfile[K]) => { setDraft((current) => ({ ...current, [key]: value })); setError(""); };
  const submit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const year = Number(draft.year);
    if (!draft.manufacturer.trim() || !draft.model.trim() || !draft.city.trim()) { setError("Preencha fabricante, modelo e cidade para salvar o veículo."); return; }
    if (!Number.isInteger(year) || year < 1950 || year > 2050) { setError("Informe um ano válido entre 1950 e 2050."); return; }
    onSave({ ...draft, manufacturer: draft.manufacturer.trim(), model: draft.model.trim(), city: draft.city.trim(), year });
  };
  const TypeIcon = draft.type === "motorcycle" ? Bike : CarFront;
  return <form className="vehicle-editor-card" onSubmit={submit} aria-label="Editar veículo">
    <div className="vehicle-editor-heading">
      <div><p className="eyebrow">CADASTRO DO VEÍCULO</p><h2>Editar identidade</h2><p className="card-subtitle">Mantenha tipo, fabricante, modelo e contexto de uso sempre atualizados.</p></div>
      <span className="vehicle-editor-badge"><TypeIcon size={14} /> {draft.type === "motorcycle" ? "Moto" : "Carro"}</span>
    </div>
    <div className="vehicle-editor-preview"><span className="vehicle-editor-preview-icon"><TypeIcon size={22} /></span><div><span>Prévia do cadastro</span><strong>{draft.manufacturer.trim() || "Fabricante"} {draft.model.trim() || "Modelo"}</strong><small>{draft.type === "motorcycle" ? "Moto" : "Carro"} · {draft.year || "Ano"} · {draft.city.trim() || "Cidade"}</small></div><span className="vehicle-editor-preview-status"><i /> Ativo</span></div>
    <div className="vehicle-editor-section"><div className="vehicle-editor-section-heading"><span>01</span><div><strong>Identidade</strong><small>Como você reconhece este veículo.</small></div></div><fieldset className="vehicle-type-picker"><legend>Tipo de veículo</legend><button className={draft.type === "car" ? "vehicle-type-option is-active" : "vehicle-type-option"} type="button" aria-pressed={draft.type === "car"} onClick={() => update("type", "car")}><CarFront size={18} /><span><strong>Carro</strong><small>Automóvel</small></span></button><button className={draft.type === "motorcycle" ? "vehicle-type-option is-active" : "vehicle-type-option"} type="button" aria-pressed={draft.type === "motorcycle"} onClick={() => update("type", "motorcycle")}><Bike size={18} /><span><strong>Moto</strong><small>Duas rodas</small></span></button></fieldset><div className="form-grid vehicle-editor-grid vehicle-editor-grid--identity"><label className="form-field"><span>Fabricante</span><input value={draft.manufacturer} onChange={(event) => update("manufacturer", event.target.value)} placeholder="Ex.: Honda" /></label><label className="form-field"><span>Modelo</span><input value={draft.model} onChange={(event) => update("model", event.target.value)} placeholder="Ex.: HR-V Touring" /></label><label className="form-field"><span>Ano</span><input inputMode="numeric" maxLength={4} value={draft.year} onChange={(event) => update("year", Number(event.target.value.replace(/\D/g, "")))} placeholder="2024" /></label></div></div>
    <div className="vehicle-editor-section vehicle-editor-section--context"><div className="vehicle-editor-section-heading"><span>02</span><div><strong>Contexto de uso</strong><small>Informações para organizar seus registros.</small></div></div><div className="form-grid vehicle-editor-grid"><label className="form-field"><span>Combustível</span><div className="select-shell"><Fuel size={15} /><select value={draft.fuel} onChange={(event) => update("fuel", event.target.value as VehicleProfile["fuel"])}><option>Gasolina</option><option>Etanol</option><option>Diesel</option></select></div></label><label className="form-field"><span>Cidade principal</span><input value={draft.city} onChange={(event) => update("city", event.target.value)} placeholder="Ex.: São Paulo" /></label></div></div>
    {error && <p className="form-error" role="alert">{error}</p>}
    <div className="vehicle-editor-footer"><div><span className="vehicle-editor-footer-dot" /> Alterações salvas somente após confirmar</div><div className="modal-actions"><button className="soft-button" type="button" onClick={onCancel}>Cancelar</button><button className="primary-button" type="submit"><Save size={15} /> Salvar veículo</button></div></div>
  </form>;
}

function VehicleFuelTable({ onAction }: { onAction: (label: string) => void }) { return <article className="surface-card vehicle-table-card"><VehicleTableHeader eyebrow="ABASTECIMENTOS" title="Histórico de combustível" description="Postos, volume, preço e odômetro em cada parada." actionLabel="Registrar abastecimento" onAction={() => onAction("Abastecimento")} /><div className="vehicle-data-table"><div className="vehicle-data-row vehicle-data-row--header"><span>Data e posto</span><span>Volume</span><span>Odômetro</span><span className="amount-cell">Valor</span></div>{vehicleFuelEntries.map((item) => <div className="vehicle-data-row" key={item.id}><span><strong>{item.station}</strong><small>{item.date} · {item.fuel}</small></span><span>{item.liters.toFixed(1).replace(".", ",")} L</span><span>{item.odometer.toLocaleString("pt-BR")} km</span><strong className="amount-cell">{formatBRL(item.amount)}</strong></div>)}</div></article>; }
function VehicleMaintenanceTable({ onAction }: { onAction: (label: string) => void }) { return <article className="surface-card vehicle-table-card"><VehicleTableHeader eyebrow="MANUTENÇÃO" title="Cuidados do veículo" description="Serviços concluídos e próximos itens planejados." actionLabel="Agendar manutenção" onAction={() => onAction("Manutenção")} /><div className="vehicle-data-table"><div className="vehicle-data-row vehicle-data-row--header"><span>Serviço</span><span>Data</span><span>Status</span><span className="amount-cell">Valor</span></div>{vehicleMaintenanceEntries.map((item) => <div className="vehicle-data-row" key={item.id}><span><strong>{item.title}</strong><small>{item.workshop} · {item.odometer.toLocaleString("pt-BR")} km</small></span><span>{item.date}</span><span><em className={`vehicle-status-chip vehicle-status-chip--${item.status === "concluída" ? "done" : "planned"}`}>{item.status}</em></span><strong className="amount-cell">{formatBRL(item.amount)}</strong></div>)}</div></article>; }
function VehicleOdometerTable({ onAction }: { onAction: (label: string) => void }) { return <article className="surface-card vehicle-table-card"><VehicleTableHeader eyebrow="QUILOMETRAGEM" title="Linha do tempo de uso" description="Registre o odômetro para acompanhar consumo e custo por km." actionLabel="Registrar quilometragem" onAction={() => onAction("Quilometragem")} /><div className="vehicle-data-table"><div className="vehicle-data-row vehicle-data-row--header"><span>Data</span><span>Odômetro</span><span>Variação</span><span>Nota</span></div>{vehicleOdometerEntries.map((item, index) => <div className="vehicle-data-row" key={item.id}><span><strong>{item.date}</strong></span><span>{item.odometer.toLocaleString("pt-BR")} km</span><span>{index === vehicleOdometerEntries.length - 1 ? "—" : `+${(item.odometer - vehicleOdometerEntries[index + 1].odometer).toLocaleString("pt-BR")} km`}</span><span>{item.note}</span></div>)}</div></article>; }
function VehicleTableHeader({ eyebrow, title, description, actionLabel, onAction }: { eyebrow: string; title: string; description: string; actionLabel: string; onAction: () => void }) { return <div className="card-header vehicle-table-header"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="card-subtitle">{description}</p></div><button className="primary-button primary-button--small" type="button" onClick={onAction}><Plus size={14} /> {actionLabel}</button></div>; }
function CalendarIcon() { return <span aria-hidden="true">◷</span>; }
